apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: shield
subjects:
  - kind: User
    name: sky
    apiGroup: rbac.authorization.k8s.io # for user, the apiGroup is always rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: read-pods
  apiGroup: rbac.authorization.k8s.io