apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: shield
  name: read-deployments
rules:
  - verbs: ["get", "watch", "list"]
    apiGroups: ["apps"]
    resources: ["deployments"]

