apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
    extraMounts:
      - hostPath: /Users/sundalei/study/learning-k8s/setup/kind-bind-mount-1
        containerPath: /some/path/in/container
  - role: worker
    extraMounts:
      - hostPath: /Users/sundalei/study/learning-k8s/setup/kind-bind-mount-2
        containerPath: /some/path/in/container