apiVersion: v1
kind: Pod
metadata:
  name: psa-pod
  namespace: psa-test
spec:
  containers:
    - name: psa-ctr
      image: nginx
      securityContext:
        privileged: false
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
