apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: books.nigelpoulton.com
spec:
  group: nigelpoulton.com
  scope: Cluster
  names:
    plural: books
    singular: book
    kind: Book
    shortNames:
      - bk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Book is the Schema for the books API
          type: object
          properties:
            spec:
              type: object
              required:
                - bookTitle
                - topic
                - edition
              description: BookSpec defines the desired state of Book
              properties:
                bookTitle:
                  type: string
                  description: The title of the book
                topic:
                  type: string
                  description: The topic of the book
                edition:
                  type: integer
                  description: The edition of the book
      additionalPrinterColumns:
        - name: Title
          type: string
          description: The title of the book
          jsonPath: .spec.bookTitle
        - name: Edition
          type: integer
          description: The edition of the book
          jsonPath: .spec.edition
